/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParamsWindow2.java
 *
 * Created on 6 juin 2016, 21:40:02
 */
package frontend;

import executer.Controller;

/**
 *
 * @author Yuri do Carmo
 */
public class ParamsWindow extends javax.swing.JFrame {

    /** Creates new form ParamsWindow2 */
    public ParamsWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        transactionFilesPath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        detectionJRadioButton = new javax.swing.JRadioButton();
        preventionRadioButton = new javax.swing.JRadioButton();
        comboBoxDectionType = new javax.swing.JComboBox();
        runSchedulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choose the directory of the transaction files:");

        transactionFilesPath.setText("/home/vinimdocarmo/workspace/2PL-protocol/transaction-files");

        jLabel2.setText("Select the deadlock type:");

        buttonGroup1.add(detectionJRadioButton);
        detectionJRadioButton.setText("Detection");
        detectionJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detectionJRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(preventionRadioButton);
        preventionRadioButton.setText("Prevention");
        preventionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preventionRadioButtonActionPerformed(evt);
            }
        });

        comboBoxDectionType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wound wait", "Wait die" }));
        comboBoxDectionType.setEnabled(false);

        runSchedulerButton.setText("Run scheduler");
        runSchedulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runSchedulerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(comboBoxDectionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(preventionRadioButton)
                            .addComponent(transactionFilesPath, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(detectionJRadioButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(runSchedulerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionFilesPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detectionJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preventionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxDectionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runSchedulerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void preventionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preventionRadioButtonActionPerformed
// TODO add your handling code here:
    comboBoxDectionType.setEnabled(true);
}//GEN-LAST:event_preventionRadioButtonActionPerformed

private void detectionJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detectionJRadioButtonActionPerformed
// TODO add your handling code here:
    comboBoxDectionType.setEnabled(false);
}//GEN-LAST:event_detectionJRadioButtonActionPerformed

private void runSchedulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runSchedulerButtonActionPerformed
// TODO add your handling code here:
    String path = this.transactionFilesPath.getText();
    int strategy = this.buttonGroup1.getSelection().getMnemonic();
    int deadlockDetectionType = this.comboBoxDectionType.getSelectedIndex();
    
    Controller.init(path, strategy, deadlockDetectionType);
}//GEN-LAST:event_runSchedulerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParamsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParamsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParamsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParamsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ParamsWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboBoxDectionType;
    private javax.swing.JRadioButton detectionJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton preventionRadioButton;
    private javax.swing.JButton runSchedulerButton;
    private javax.swing.JTextField transactionFilesPath;
    // End of variables declaration//GEN-END:variables
}
